### ISSUE TITLE
fun String.toUpperCase(): String' is deprecated. Use uppercase() instead.

### ISSUE THREAD

**Issue by roma7481** [mustafa-707/sim_card_code#1]
after upgrading kotlin from 1.9.24 to id "org.jetbrains.kotlin.android" version "2.1.0" getting the following

> 
> e: file:///Users/xxxxxxxxx/.pub-cache/hosted/pub.dev/sim_card_code-0.0.2/android/src/main/kotlin/com/example/sim_card_code/SimCardCodePlugin.kt:35:34 'fun String.toUpperCase(): String' is deprecated. Use uppercase() instead.
> 3 warnings
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':sim_card_code:compileDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
>    > Compilation error. See log for more details
>

**Comment by mustafa-707** [comment]
Hope it fixed on new version 

`sim_card_code: ^0.0.3`

please close the issue if it got fixed 

Thank you for sharing this

**Comment by roma7481** [comment]
yes, that seems to work, thank you for the fast fix
